In [ ]:
import numpy as np
a = np.array(range(1, 11), dtype=float)
print(a)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
a = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]], dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
a = np.random.randint(1, 11, (5, 5))
print(a)

[[ 6  8  7  3  4]
 [ 9  8  6  3  1]
 [ 3  7  6  8  9]
 [10  7  3  5  8]
 [ 3  9  2  8  8]]


In [ ]:
a = np.random.rand(4, 4)
print(a)

[[0.45390576 0.1818486  0.72118412 0.97695505]
 [0.0793452  0.5073473  0.44435989 0.56691394]
 [0.3190294  0.20885099 0.57153935 0.5650627 ]
 [0.70741594 0.89447801 0.61150441 0.55817312]]


In [ ]:
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)
print("Вектори a і b:", "\n", a, "\n", b)
print("   Додавання:", a + b)
print("   Віднімання:", a - b)
print("   Множення:", a * b)

Вектори a і b: 
 [ 5 10  9  1  4] 
 [ 1  8  1 10  9]
   Додавання: [ 6 18 10 11 13]
   Віднімання: [ 4  2  8 -9 -5]
   Множення: [ 5 80  9 10 36]


In [ ]:
a = np.random.randint(1, 11, 7)
b = np.random.randint(1, 11, 7)
scalar = np.dot(a, b)
print("Вектори:\n", a, "\n", b, "\nДобуток:", scalar)

Вектори:
 [4 9 3 2 2 6 9] 
 [2 5 8 8 2 5 4] 
Добуток: 163


In [ ]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 3))
a_mul_b = np.dot(a, b)
print("Матриці:", "\n", a, "\n", b)
print("Добуток:", "\n", a_mul_b)

Матриці: 
 [[ 8  9]
 [10  2]] 
 [[4 3 3]
 [4 6 2]]
Добуток: 
 [[68 78 42]
 [48 42 34]]


In [ ]:
a = np.random.randint(1, 11, (3, 3))
a_inv = np.linalg.inv(a)
print("Матриця:\n", a, "\nОбернена матриця:\n", a_inv)

Матриця:
 [[ 1  3  2]
 [ 7  7  3]
 [ 4  5 10]] 
Обернена матриця:
 [[-0.52380952  0.19047619  0.04761905]
 [ 0.55238095 -0.01904762 -0.1047619 ]
 [-0.06666667 -0.06666667  0.13333333]]


In [ ]:
a = np.random.rand(4, 4)
print("Матриця:\n", a)
print("Транспонована:\n", a.T)

Матриця:
 [[0.52629512 0.33246429 0.82400145 0.94494864]
 [0.14009873 0.84167756 0.90237289 0.08771345]
 [0.35843841 0.77609648 0.26828915 0.7846247 ]
 [0.90161203 0.85962016 0.93924216 0.25045174]]
Транспонована:
 [[0.52629512 0.14009873 0.35843841 0.90161203]
 [0.33246429 0.84167756 0.77609648 0.85962016]
 [0.82400145 0.90237289 0.26828915 0.93924216]
 [0.94494864 0.08771345 0.7846247  0.25045174]]


In [ ]:
a = np.random.randint(1, 11, (3, 4))
b = np.random.randint(1, 11, 4)
a_mul_b = np.dot(a, b)
print("Матриця:", "\n", a, "\nВектор:\n", b)
print("Добуток:\n", a_mul_b)

Матриця: 
 [[ 2  4  1 10]
 [ 3  6  3  7]
 [ 2  2  6  4]] 
Вектор:
 [4 6 6 8]
Добуток:
 [118 122  88]


In [ ]:
a = np.random.rand(2, 3)
b = np.random.rand(3)
a_mul_b = np.dot(a, b)
print("Матриця:", "\n", a, "\nВектор:\n", b)
print("Добуток:\n", a_mul_b)

Матриця: 
 [[0.86023424 0.77958692 0.62148692]
 [0.32428311 0.07374479 0.02238568]] 
Вектор
 [0.64205133 0.08968952 0.4071719 ]
Добуток:
 [0.87528733 0.22393536]


In [ ]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
elem_mul = a * b
print("Матриці:", "\n", a, "\n\n", b)
print("Поелементне множення:\n", elem_mul)

Матриці: 
 [[5 1]
 [9 4]] 

 [[ 5  3]
 [ 5 10]]

12. Поелементне множення:
 [[25  3]
 [45 40]]


In [ ]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
a_mul_b = np.dot(a, b)
print("Матриці:", "\n", a, "\n\n", b)
print("Добуток двох матриць:\n", a_mul_b)

Матриці: 
 [[10  1]
 [ 3  9]] 

 [[7 2]
 [7 5]]
Добуток двох матриць:
 [[77 25]
 [84 51]]


In [ ]:
a = np.random.randint(1, 101, (5, 5))
sum_a = np.sum(a)
print("Матриця:\n", a, "\nСума елементів:", sum_a)

Матриця:
 [[71 78  4 33 49]
 [51 70 64 64 38]
 [79 82 64 47 15]
 [11 86 31 76 17]
 [57 59 99 85 43]] 
Сума елементів: 1373


In [ ]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))
diff = a - b
print("Матриці:", "\n", a, "\n\n", b)
print("Різниця:\n", diff)

Матриці: 
 [[9 4 3 3]
 [9 9 9 8]
 [3 2 3 4]
 [3 2 3 1]] 

 [[10  7 10  7]
 [ 4  5  2  9]
 [ 3  4  3  6]
 [ 4  4  5 10]]
Різниця:
 [[-1 -3 -7 -4]
 [ 5  4  7 -1]
 [ 0 -2  0 -2]
 [-1 -2 -2 -9]]


In [ ]:
a = np.random.rand(3, 3)
row_sums = np.sum(a, axis=1).reshape(-1, 1)
print("Матриця:", "\n", a)
print("\nСуми елементів рядків:\n", row_sums)

Матриця: 
 [[0.53609197 0.31947512 0.60516934]
 [0.19032948 0.76485133 0.4565603 ]
 [0.29167757 0.07676997 0.72313423]]

Суми елементів рядків:
 [[1.46073644]
 [1.41174111]
 [1.09158177]]


In [ ]:
a = np.random.randint(1, 11, (3, 4))
squares = a ** 2
print("Матриця:\n", a, "\nМатриця квадратів:\n", squares)

Матриця:
 [[ 2  5 10  1]
 [ 2  1  7  5]
 [ 8  4  8  2]] 
Матриця квадратів:
 [[  4  25 100   1]
 [  4   1  49  25]
 [ 64  16  64   4]]


In [ ]:
a = np.random.randint(1, 51, 4)
sq_roots = np.sqrt(a)
print("Вектор:\n", a, "\nКвадратні корені:\n", sq_roots)

Вектор:
 [16 40 20 20] 
Квадратні корені:
 [4.         6.32455532 4.47213595 4.47213595]
